#################################
#     Advent of Code Tests      #
#         Year: 2024            #
#           Day: 01             #
#################################
[test.test_01]
part = 1
input = """3   4
4   3
2   5
1   3
3   9
3   3"""
answer = 11

[test.test_02]
part = 2
input = """3   4
4   3
2   5
1   3
3   9
3   3"""
answer = 31
